sonar.projectKey=jobportal
sonar.projectName=JobPortal
sonar.sources=.
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/venv/**,**/.git/**,**/*.java,**/target/**,**/hello-java/**
